export const keys = [
    'C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'
];

export const mostCommonSongs = {
    "songs": [
        { "title": "Autumn Leaves", "artist": "Chet Baker", "chords": "ii-V-I", "key": "G", "tempo": 90, "genre": "Jazz" },
        { "title": "All of Me", "artist": "Billie Holiday", "chords": "I-IV-V", "key": "C", "tempo": 100, "genre": "Jazz" },
        { "title": "Blue Monk", "artist": "Thelonious Monk", "chords": "I-vi-IV-V", "key": "Bb", "tempo": 85, "genre": "Jazz" },
        { "title": "Take Five", "artist": "Dave Brubeck", "chords": "I-V-vi-IV", "key": "E", "tempo": 93, "genre": "Jazz" },
        { "title": "Summertime", "artist": "Ella Fitzgerald", "chords": "I-vi-ii-V", "key": "D", "tempo": 75, "genre": "Jazz" },
        { "title": "Fly Me to the Moon", "artist": "Frank Sinatra", "chords": "I-V-IV", "key": "C", "tempo": 100, "genre": "Jazz" },
        { "title": "My Funny Valentine", "artist": "Chet Baker", "chords": "IV-V-I", "key": "C", "tempo": 68, "genre": "Jazz" },
        { "title": "Misty", "artist": "Erroll Garner", "chords": "vi-IV-I-V", "key": "Eb", "tempo": 72, "genre": "Jazz" },
        { "title": "Round Midnight", "artist": "Thelonious Monk", "chords": "I-IV-vi-V", "key": "Eb", "tempo": 65, "genre": "Jazz" },
        { "title": "Body and Soul", "artist": "Coleman Hawkins", "chords": "I-IV-I-V", "key": "Db", "tempo": 70, "genre": "Jazz" },
        { "title": "In a Sentimental Mood", "artist": "Duke Ellington", "chords": "I-IV-vi-IV", "key": "C", "tempo": 70, "genre": "Jazz" },
        { "title": "Georgia on My Mind", "artist": "Ray Charles", "chords": "vi-IV-vi-V", "key": "F", "tempo": 72, "genre": "Jazz" },
        { "title": "Night and Day", "artist": "Frank Sinatra", "chords": "I-V-vi-iii-IV-I-IV-V", "key": "C", "tempo": 120, "genre": "Jazz" },
        { "title": "How High the Moon", "artist": "Ella Fitzgerald", "chords": "I-iii-IV-V", "key": "G", "tempo": 95, "genre": "Jazz" },
        { "title": "Ain't Misbehavin'", "artist": "Fats Waller", "chords": "I-IV-V-vi", "key": "C", "tempo": 92, "genre": "Jazz" },
        { "title": "All the Things You Are", "artist": "Charlie Parker", "chords": "I-iii-IV-ii", "key": "Ab", "tempo": 85, "genre": "Jazz" },
        { "title": "Stella by Starlight", "artist": "Miles Davis", "chords": "I-V-IV-vi", "key": "Bb", "tempo": 86, "genre": "Jazz" },
        { "title": "Desafinado", "artist": "Stan Getz", "chords": "I-ii-IV-V", "key": "F", "tempo": 94, "genre": "Jazz" },
        { "title": "So What", "artist": "Miles Davis", "chords": "ii-IV-I-V", "key": "D", "tempo": 82, "genre": "Jazz" },
        { "title": "Lullaby of Birdland", "artist": "Sarah Vaughan", "chords": "I-V-IV-ii", "key": "F", "tempo": 125, "genre": "Jazz" },
        { "title": "My Favorite Things", "artist": "John Coltrane", "chords": "I-IV-V-ii", "key": "Eb", "tempo": 100, "genre": "Jazz" },
        { "title": "Cantaloupe Island", "artist": "Herbie Hancock", "chords": "ii-V-IV-I", "key": "F", "tempo": 115, "genre": "Jazz" },
        { "title": "Freddie Freeloader", "artist": "Miles Davis", "chords": "I-V-vi-ii-IV-I-IV-V", "key": "Bb", "tempo": 124, "genre": "Jazz" },
        { "title": "Dolphin Dance", "artist": "Herbie Hancock", "chords": "I-vi-ii-IV-V", "key": "Eb", "tempo": 110, "genre": "Jazz" },
        { "title": "Well, You Needn't", "artist": "Thelonious Monk", "chords": "I-IV-V-iii", "key": "F", "tempo": 95, "genre": "Jazz" },
        { "title": "Ornithology", "artist": "Charlie Parker", "chords": "I-ii-iii-IV", "key": "Bb", "tempo": 105, "genre": "Jazz" },
        { "title": "Maiden Voyage", "artist": "Herbie Hancock", "chords": "IV-V-vi-iii", "key": "D", "tempo": 130, "genre": "Jazz" },
        { "title": "Django", "artist": "Modern Jazz Quartet", "chords": "I-vi-IV-I-V-IV", "key": "C", "tempo": 92, "genre": "Jazz" },
        { "title": "Song for My Father", "artist": "Horace Silver", "chords": "vi-V-vi-IV", "key": "F", "tempo": 110, "genre": "Jazz" },
        { "title": "Spain", "artist": "Chick Corea", "chords": "I-V-vi-IV-V", "key": "G", "tempo": 98, "genre": "Jazz" },
        { "title": "Wave", "artist": "Antonio Carlos Jobim", "chords": "I-ii-IV-V-IV", "key": "Eb", "tempo": 125, "genre": "Jazz" },
        { "title": "Footprints", "artist": "Wayne Shorter", "chords": "IV-I-V-vi", "key": "C", "tempo": 115, "genre": "Jazz" },
        { "title": "Equinox", "artist": "John Coltrane", "chords": "I-IV-I-V-IV", "key": "C", "tempo": 88, "genre": "Jazz" },
        { "title": "Stolen Moments", "artist": "Oliver Nelson", "chords": "IV-V-IV-V-I", "key": "C", "tempo": 100, "genre": "Jazz" },
        { "title": "Waltz for Debby", "artist": "Bill Evans", "chords": "I-V-vi-IV-iii-IV", "key": "F", "tempo": 85, "genre": "Jazz" },
        { "title": "Blue in Green", "artist": "Miles Davis", "chords": "I-vi-V-IV-V", "key": "G", "tempo": 105, "genre": "Jazz" },
        { "title": "Groovin' High", "artist": "Dizzy Gillespie", "chords": "IV-V-vi-V-IV", "key": "Eb", "tempo": 90, "genre": "Jazz" },
        { "title": "Epistrophy", "artist": "Thelonious Monk", "chords": "IV-I-IV-V", "key": "F", "tempo": 115, "genre": "Jazz" },
        { "title": "Milestones", "artist": "Miles Davis", "chords": "I-IV-V-IV-V", "key": "Bb", "tempo": 130, "genre": "Jazz" },
        { "title": "In Walked Bud", "artist": "Thelonious Monk", "chords": "vi-ii-V-I", "key": "C", "tempo": 125, "genre": "Jazz" },
        { "title": "Cherokee", "artist": "Charlie Parker", "chords": "I-V-vi-iii-IV", "key": "Bb", "tempo": 110, "genre": "Jazz" },
        { "title": "Solar", "artist": "Miles Davis", "chords": "I-vi-IV-V-IV", "key": "C", "tempo": 135, "genre": "Jazz" },
        { "title": "Nardis", "artist": "Bill Evans", "chords": "I-V-IV-vi-IV", "key": "D", "tempo": 120, "genre": "Jazz" },
        { "title": "Straight, No Chaser", "artist": "Thelonious Monk", "chords": "I-V-IV-I-IV", "key": "Bb", "tempo": 110, "genre": "Jazz" },
        { "title": "Stompin' at the Savoy", "artist": "Benny Goodman", "chords": "vi-IV-ii-V-I", "key": "C", "tempo": 120, "genre": "Jazz" },
        { "title": "A Night in Tunisia", "artist": "Dizzy Gillespie", "chords": "I-IV-I-V", "key": "Dm", "tempo": 160, "genre": "Jazz" },
        { "title": "Afro Blue", "artist": "John Coltrane", "chords": "ii-V-IV-I", "key": "Dm", "tempo": 110, "genre": "Jazz" },
        { "title": "Angel Eyes", "artist": "Ella Fitzgerald", "chords": "I-vi-ii-V", "key": "G", "tempo": 65, "genre": "Jazz" },
        { "title": "But Not for Me", "artist": "Chet Baker", "chords": "I-vi-ii-V", "key": "G", "tempo": 120, "genre": "Jazz" },
        { "title": "Caravan", "artist": "Duke Ellington", "chords": "vi-IV-I-V", "key": "Am", "tempo": 140, "genre": "Jazz" },
        { "title": "Cheek to Cheek", "artist": "Ella Fitzgerald", "chords": "I-vi-ii-V", "key": "C", "tempo": 115, "genre": "Jazz" },
        { "title": "Darn That Dream", "artist": "Miles Davis", "chords": "I-IV-I-V", "key": "F", "tempo": 90, "genre": "Jazz" },
        { "title": "Donna Lee", "artist": "Charlie Parker", "chords": "I-vi-ii-V", "key": "Bb", "tempo": 180, "genre": "Jazz" },
        { "title": "Fascinating Rhythm", "artist": "Ella Fitzgerald", "chords": "I-vi-ii-V", "key": "C", "tempo": 160, "genre": "Jazz" },
        { "title": "Footprints", "artist": "Miles Davis", "chords": "I-vi-ii-V", "key": "Cm", "tempo": 110, "genre": "Jazz" },
        { "title": "Four", "artist": "Miles Davis", "chords": "ii-V-I", "key": "F", "tempo": 190, "genre": "Jazz" },
        { "title": "Giant Steps", "artist": "John Coltrane", "chords": "I-iii-VI-ii-V", "key": "B", "tempo": 200, "genre": "Jazz" },
        { "title": "Goodbye Pork Pie Hat", "artist": "Charles Mingus", "chords": "I-vi-IV-V", "key": "Eb", "tempo": 70, "genre": "Jazz" },
        { "title": "In a Mellow Tone", "artist": "Duke Ellington", "chords": "I-IV-I-V", "key": "C", "tempo": 120, "genre": "Jazz" },
        { "title": "In Your Own Sweet Way", "artist": "Dave Brubeck", "chords": "I-vi-ii-V", "key": "Eb", "tempo": 120, "genre": "Jazz" },
        { "title": "It Don't Mean a Thing", "artist": "Duke Ellington", "chords": "I-vi-ii-V", "key": "G", "tempo": 180, "genre": "Jazz" },
        { "title": "Jeepers Creepers", "artist": "Louis Armstrong", "chords": "I-IV-I-V", "key": "F", "tempo": 150, "genre": "Jazz" },
        { "title": "Just Friends", "artist": "Charlie Parker", "chords": "I-vi-ii-V", "key": "F", "tempo": 180, "genre": "Jazz" },
        { "title": "Lester Leaps In", "artist": "Count Basie", "chords": "I-vi-ii-V", "key": "Bb", "tempo": 180, "genre": "Jazz" },
        { "title": "Lush Life", "artist": "John Coltrane", "chords": "I-vi-ii-V", "key": "Eb", "tempo": 90, "genre": "Jazz" },
        { "title": "Mack the Knife", "artist": "Louis Armstrong", "chords": "I-vi-ii-V", "key": "C", "tempo": 140, "genre": "Jazz" },
        { "title": "Manha de Carnaval", "artist": "Stan Getz", "chords": "I-vi-ii-V", "key": "G", "tempo": 120, "genre": "Jazz" },
        { "title": "Meditation", "artist": "Antonio Carlos Jobim", "chords": "I-vi-ii-V", "key": "D", "tempo": 120, "genre": "Jazz" },
        { "title": "Moonlight in Vermont", "artist": "Ella Fitzgerald", "chords": "I-vi-ii-V", "key": "F", "tempo": 100, "genre": "Jazz" },
        { "title": "Mr. P.C.", "artist": "John Coltrane", "chords": "ii-V-I", "key": "C", "tempo": 130, "genre": "Jazz" },
        { "title": "My Foolish Heart", "artist": "Bill Evans", "chords": "I-vi-ii-V", "key": "D", "tempo": 100, "genre": "Jazz" },
        { "title": "My One and Only Love", "artist": "John Coltrane", "chords": "I-vi-ii-V", "key": "C", "tempo": 85, "genre": "Jazz" },
        { "title": "My Romance", "artist": "Ella Fitzgerald", "chords": "I-vi-ii-V", "key": "C", "tempo": 120, "genre": "Jazz" },
        { "title": "Naima", "artist": "John Coltrane", "chords": "ii-V-I", "key": "G", "tempo": 80, "genre": "Jazz" },
        { "title": "Nica's Dream", "artist": "Horace Silver", "chords": "I-vi-ii-V", "key": "C", "tempo": 140, "genre": "Jazz" },
        { "title": "Night Train", "artist": "Oscar Peterson", "chords": "I-vi-ii-V", "key": "C", "tempo": 130, "genre": "Jazz" },
        { "title": "Oleo", "artist": "Sonny Rollins", "chords": "I-vi-ii-V", "key": "Bb", "tempo": 170, "genre": "Jazz" },
        { "title": "Oleo", "artist": "Miles Davis", "chords": "I-vi-ii-V", "key": "Bb", "tempo": 180, "genre": "Jazz" },
        { "title": "One Note Samba", "artist": "Stan Getz", "chords": "I-vi-ii-V", "key": "Bb", "tempo": 150, "genre": "Jazz" },
        { "title": "Out of Nowhere", "artist": "Charlie Parker", "chords": "I-vi-ii-V", "key": "G", "tempo": 180, "genre": "Jazz" },
        { "title": "Over the Rainbow", "artist": "Ella Fitzgerald", "chords": "I-vi-ii-V", "key": "C", "tempo": 120, "genre": "Jazz" },
        { "title": "Polka Dots and Moonbeams", "artist": "Bill Evans", "chords": "I-vi-ii-V", "key": "C", "tempo": 85, "genre": "Jazz" },
        { "title": "Satin Doll", "artist": "Duke Ellington", "chords": "I-vi-ii-V", "key": "C", "tempo": 140, "genre": "Jazz" },
        { "title": "Scrapple from the Apple", "artist": "Charlie Parker", "chords": "I-vi-ii-V", "key": "G", "tempo": 230, "genre": "Jazz" },
        { "title": "Sister Sadie", "artist": "Horace Silver", "chords": "I-vi-ii-V", "key": "C", "tempo": 140, "genre": "Jazz" },
        { "title": "Softly, As in a Morning Sunrise", "artist": "Sonny Rollins", "chords": "I-vi-ii-V", "key": "C", "tempo": 150, "genre": "Jazz" },
        { "title": "Solar", "artist": "Miles Davis", "chords": "I-vi-ii-V", "key": "Cm", "tempo": 135, "genre": "Jazz" },
        { "title": "Someday My Prince Will Come", "artist": "Miles Davis", "chords": "I-vi-ii-V", "key": "Bb", "tempo": 80, "genre": "Jazz" },
        { "title": "Sonnymoon for Two", "artist": "Sonny Rollins", "chords": "I-vi-ii-V", "key": "C", "tempo": 180, "genre": "Jazz" },
        { "title": "Speak Low", "artist": "Ella Fitzgerald", "chords": "I-vi-ii-V", "key": "G", "tempo": 150, "genre": "Jazz" },
        { "title": "St. Thomas", "artist": "Sonny Rollins", "chords": "I-vi-ii-V", "key": "C", "tempo": 160, "genre": "Jazz" },
        { "title": "Sweet Georgia Brown", "artist": "Django Reinhardt", "chords": "I-vi-ii-V", "key": "C", "tempo": 180, "genre": "Jazz" },
        { "title": "Take the 'A' Train", "artist": "Duke Ellington", "chords": "I-vi-ii-V", "key": "C", "tempo": 160, "genre": "Jazz" },
        { "title": "The Girl from Ipanema", "artist": "Antonio Carlos Jobim", "chords": "I-vi-ii-V", "key": "F", "tempo": 120, "genre": "Jazz" },
        { "title": "The Song Is You", "artist": "Charlie Parker", "chords": "I-vi-ii-V", "key": "Eb", "tempo": 180, "genre": "Jazz" },
        { "title": "There Is No Greater Love", "artist": "Miles Davis", "chords": "I-vi-ii-V", "key": "Eb", "tempo": 150, "genre": "Jazz" },
        { "title": "There Will Never Be Another You", "artist": "Charlie Parker", "chords": "I-vi-ii-V", "key": "C", "tempo": 180, "genre": "Jazz" },
        { "title": "They Can't Take That Away from Me", "artist": "Ella Fitzgerald", "chords": "I-vi-ii-V", "key": "Eb", "tempo": 120, "genre": "Jazz" },
        { "title": "Tune Up", "artist": "Miles Davis", "chords": "ii-V-I", "key": "Bb", "tempo": 180, "genre": "Jazz" },
        { "title": "Turn Out the Stars", "artist": "Bill Evans", "chords": "I-vi-ii-V", "key": "C", "tempo": 150, "genre": "Jazz" },
        { "title": "Unit 7", "artist": "Wes Montgomery", "chords": "I-vi-ii-V", "key": "G", "tempo": 180, "genre": "Jazz" },
        { "title": "Up Jumped Spring", "artist": "Freddie Hubbard", "chords": "I-vi-ii-V", "key": "Bb", "tempo": 120, "genre": "Jazz" },
        { "title": "Valse Hot", "artist": "Sonny Rollins", "chords": "I-vi-ii-V", "key": "C", "tempo": 190, "genre": "Jazz" },
        { "title": "Well You Needn't", "artist": "Thelonious Monk", "chords": "I-vi-ii-V", "key": "F", "tempo": 170, "genre": "Jazz" },
        { "title": "What Is This Thing Called Love?", "artist": "Ella Fitzgerald", "chords": "I-vi-ii-V", "key": "C", "tempo": 140, "genre": "Jazz" },
        { "title": "Whisper Not", "artist": "Benny Golson", "chords": "I-vi-ii-V", "key": "G", "tempo": 170, "genre": "Jazz" },
        { "title": "Without a Song", "artist": "Sonny Rollins", "chords": "I-vi-ii-V", "key": "G", "tempo": 140, "genre": "Jazz" },
        { "title": "Yesterdays", "artist": "Ella Fitzgerald", "chords": "I-vi-ii-V", "key": "C", "tempo": 140, "genre": "Jazz" },
        { "title": "You and the Night and the Music", "artist": "Bill Evans", "chords": "I-vi-ii-V", "key": "Eb", "tempo": 160, "genre": "Jazz" },
        { "title": "You Stepped Out of a Dream", "artist": "Herbie Hancock", "chords": "I-vi-ii-V", "key": "C", "tempo": 180, "genre": "Jazz" },
        { "title": "Crossroads", "artist": "Cream", "chords": "I-IV-V", "key": "A", "tempo": 100, "genre": "Blues Rock" },
        { "title": "Sweet Home Chicago", "artist": "Robert Johnson", "chords": "I-IV-V", "key": "E", "tempo": 120, "genre": "Delta Blues" },
        { "title": "Hoochie Coochie Man", "artist": "Muddy Waters", "chords": "I-IV-V", "key": "E", "tempo": 90, "genre": "Chicago Blues" },
        { "title": "Red House", "artist": "Jimi Hendrix", "chords": "I-IV-V", "key": "B", "tempo": 80, "genre": "Blues Rock" },
        { "title": "Born Under a Bad Sign", "artist": "Albert King", "chords": "I-IV-I-V", "key": "C", "tempo": 110, "genre": "Blues Rock" },
        { "title": "Stormy Monday", "artist": "T-Bone Walker", "chords": "I-IV-I-V", "key": "G", "tempo": 65, "genre": "Blues" },
        { "title": "I'm Tore Down", "artist": "Freddie King", "chords": "I-IV-V", "key": "A", "tempo": 120, "genre": "Electric Blues" },
        { "title": "Every Day I Have the Blues", "artist": "B.B. King", "chords": "I-IV-V", "key": "F", "tempo": 85, "genre": "Blues" },
        { "title": "Key to the Highway", "artist": "Big Bill Broonzy", "chords": "I-IV-V", "key": "C", "tempo": 95, "genre": "Delta Blues" },
        { "title": "Catfish Blues", "artist": "Robert Petway", "chords": "I-IV-V", "key": "G", "tempo": 110, "genre": "Delta Blues" },
        { "title": "Statesboro Blues", "artist": "Blind Willie McTell", "chords": "I-IV-V", "key": "G", "tempo": 120, "genre": "Delta Blues" },
        { "title": "Mannish Boy", "artist": "Muddy Waters", "chords": "I-IV-V", "key": "E", "tempo": 95, "genre": "Chicago Blues" },
        { "title": "Pride and Joy", "artist": "Stevie Ray Vaughan", "chords": "I-IV-V", "key": "E", "tempo": 110, "genre": "Blues Rock" },
        { "title": "Good Morning Little Schoolgirl", "artist": "Sonny Boy Williamson I", "chords": "I-IV-V", "key": "E", "tempo": 100, "genre": "Chicago Blues" },
        { "title": "Baby Please Don't Go", "artist": "Big Joe Williams", "chords": "I-IV-V", "key": "A", "tempo": 125, "genre": "Delta Blues" },
        { "title": "I Can't Quit You Baby", "artist": "Willie Dixon", "chords": "I-IV-V", "key": "F", "tempo": 80, "genre": "Chicago Blues" },
        { "title": "Sweet Little Angel", "artist": "B.B. King", "chords": "I-IV-I-V", "key": "A", "tempo": 95, "genre": "Electric Blues" },
        { "title": "Further On Up the Road", "artist": "Bobby \"Blue\" Bland", "chords": "I-IV-V", "key": "D", "tempo": 105, "genre": "Electric Blues" },
        { "title": "Love in Vain", "artist": "Robert Johnson", "chords": "I-IV-I-V", "key": "A", "tempo": 80, "genre": "Delta Blues" },
        { "title": "Call It Stormy Monday (But Tuesday Is Just As Bad)", "artist": "T-Bone Walker", "chords": "I-IV-I-V", "key": "C", "tempo": 70, "genre": "Blues" },
        { "title": "Help Me", "artist": "Sonny Boy Williamson II", "chords": "I-IV-V", "key": "G", "tempo": 95, "genre": "Chicago Blues" },
        { "title": "Little Red Rooster", "artist": "Howlin' Wolf", "chords": "I-IV-V", "key": "E", "tempo": 85, "genre": "Chicago Blues" },
        { "title": "Dust Bowl", "artist": "Joe Bonamassa", "chords": "I-IV-I-V", "key": "E", "tempo": 100, "genre": "Blues Rock" },
        { "title": "Key to the Highway", "artist": "Eric Clapton", "chords": "I-IV-I-V", "key": "G", "tempo": 90, "genre": "Blues Rock" },
        { "title": "Statesboro Blues", "artist": "The Allman Brothers Band", "chords": "I-IV-V", "key": "E", "tempo": 120, "genre": "Blues Rock" },
        { "title": "Messin' With The Kid", "artist": "Junior Wells", "chords": "I-IV-V", "key": "A", "tempo": 105, "genre": "Chicago Blues" },
        { "title": "Cross Road Blues", "artist": "Robert Johnson", "chords": "I-IV-V", "key": "A", "tempo": 90, "genre": "Delta Blues" },
        { "title": "Wang Dang Doodle", "artist": "Koko Taylor", "chords": "I-IV-V", "key": "G", "tempo": 100, "genre": "Chicago Blues" },
        { "title": "I Just Want to Make Love to You", "artist": "Foghat", "chords": "I-IV-V", "key": "E", "tempo": 120, "genre": "Blues Rock" },
        { "title": "Going Down", "artist": "Freddie King", "chords": "I-IV-V", "key": "G", "tempo": 110, "genre": "Blues Rock" },
        { "title": "Spoonful", "artist": "Howlin' Wolf", "chords": "I-IV-V", "key": "E", "tempo": 90, "genre": "Chicago Blues" },
        { "title": "Smokestack Lightnin'", "artist": "Howlin' Wolf", "chords": "I-IV-V", "key": "E", "tempo": 95, "genre": "Chicago Blues" },
        { "title": "Thrill Is Gone", "artist": "B.B. King", "chords": "I-bVII-IV-I", "key": "Bb", "tempo": 75, "genre": "Blues" },
        { "title": "Mystery Train", "artist": "Elvis Presley", "chords": "I-IV-V", "key": "A", "tempo": 105, "genre": "Rock and Roll" },
        { "title": "Texas Flood", "artist": "Stevie Ray Vaughan", "chords": "I-IV-V", "key": "G", "tempo": 80, "genre": "Blues Rock" },
        { "title": "Dust My Broom", "artist": "Elmore James", "chords": "I-IV-V", "key": "E", "tempo": 100, "genre": "Chicago Blues" },
        { "title": "Little Wing", "artist": "Jimi Hendrix", "chords": "I-IV-V", "key": "A", "tempo": 65, "genre": "Blues Rock" },
        { "title": "Voodoo Child (Slight Return)", "artist": "Jimi Hendrix", "chords": "I-IV-V", "key": "E", "tempo": 70, "genre": "Blues Rock" },
        { "title": "I Ain't Superstitious", "artist": "Jeff Beck", "chords": "I-IV-V", "key": "E", "tempo": 105, "genre": "Blues Rock" },
        { "title": "Got My Mojo Working", "artist": "Muddy Waters", "chords": "I-IV-V", "key": "G", "tempo": 95, "genre": "Chicago Blues" },
        { "title": "I Just Wanna Make Love to You", "artist": "Muddy Waters", "chords": "I-IV-V", "key": "E", "tempo": 115, "genre": "Chicago Blues" },
        { "title": "Rollin' and Tumblin'", "artist": "Muddy Waters", "chords": "I-IV-V", "key": "E", "tempo": 100, "genre": "Chicago Blues" },
        { "title": "Crosscut Saw", "artist": "Albert King", "chords": "I-IV-V", "key": "G", "tempo": 110, "genre": "Electric Blues" },
        { "title": "Bright Lights, Big City", "artist": "Jimmy Reed", "chords": "I-IV-V", "key": "G", "tempo": 90, "genre": "Chicago Blues" },
        { "title": "Sitting on Top of the World", "artist": "Mississippi Sheiks", "chords": "I-IV-I-V", "key": "E", "tempo": 95, "genre": "Delta Blues" },
        { "title": "Milk Cow Blues", "artist": "Kokomo Arnold", "chords": "I-IV-I-V", "key": "C", "tempo": 105, "genre": "Delta Blues" },
        { "title": "Rock Me Baby", "artist": "B.B. King", "chords": "I-IV-V", "key": "G", "tempo": 95, "genre": "Electric Blues" },
        { "title": "Mannish Boy", "artist": "Jimi Hendrix", "chords": "I-IV-V", "key": "E", "tempo": 95, "genre": "Blues Rock" },
        { "title": "Walking Blues", "artist": "Robert Johnson", "chords": "I-IV-I-V", "key": "E", "tempo": 120, "genre": "Delta Blues" },
        { "title": "Mystery Train", "artist": "Junior Parker", "chords": "I-IV-V", "key": "A", "tempo": 105, "genre": "Rock and Roll" },
        { "title": "Stormy Monday Blues", "artist": "Bobby \"Blue\" Bland", "chords": "I-IV-V", "key": "G", "tempo": 75, "genre": "Blues" },
        { "title": "I Can't Be Satisfied", "artist": "Muddy Waters", "chords": "I-IV-V", "key": "E", "tempo": 110, "genre": "Chicago Blues" },
        { "title": "Cocaine", "artist": "Eric Clapton", "chords": "I-IV-V", "key": "E", "tempo": 130, "genre": "Blues Rock" },
        { "title": "See That My Grave Is Kept Clean", "artist": "Blind Lemon Jefferson", "chords": "I-IV-V", "key": "E", "tempo": 85, "genre": "Delta Blues" },
        { "title": "Baby What's Wrong", "artist": "The Animals", "chords": "I-IV-V", "key": "G", "tempo": 95, "genre": "Blues Rock" },
        { "title": "Catfish Blues", "artist": "Buddy Guy", "chords": "I-IV-V", "key": "G", "tempo": 120, "genre": "Chicago Blues" },
        { "title": "I Ain't Superstitious", "artist": "Willie Dixon", "chords": "I-IV-V", "key": "E", "tempo": 105, "genre": "Chicago Blues" },
        { "title": "Death Letter Blues", "artist": "Son House", "chords": "I-IV-I-V", "key": "D", "tempo": 80, "genre": "Delta Blues" },
        { "title": "Crawlin' King Snake", "artist": "John Lee Hooker", "chords": "I-IV-V", "key": "E", "tempo": 100, "genre": "Delta Blues" },
        { "title": "I'm Ready", "artist": "Muddy Waters", "chords": "I-IV-V", "key": "A", "tempo": 100, "genre": "Chicago Blues" },
        { "title": "Worried Life Blues", "artist": "Big Maceo", "chords": "I-IV-V", "key": "G", "tempo": 90, "genre": "Chicago Blues" },
        { "title": "Hoochie Coochie Man", "artist": "Jimi Hendrix", "chords": "I-IV-V", "key": "E", "tempo": 90, "genre": "Blues Rock" },
        { "title": "Reconsider Baby", "artist": "Elvis Presley", "chords": "I-IV-V", "key": "G", "tempo": 80, "genre": "Blues Rock" },
        { "title": "Mojo Hand", "artist": "Lightnin' Hopkins", "chords": "I-IV-V", "key": "E", "tempo": 110, "genre": "Delta Blues" },
        { "title": "Let the Good Times Roll", "artist": "Louis Jordan", "chords": "I-IV-V", "key": "C", "tempo": 100, "genre": "Jump Blues" },
        { "title": "Wang Dang Doodle", "artist": "Howlin' Wolf", "chords": "I-IV-V", "key": "G", "tempo": 100, "genre": "Chicago Blues" },
        { "title": "All Your Love (I Miss Loving)", "artist": "Otis Rush", "chords": "I-IV-V", "key": "A", "tempo": 95, "genre": "Chicago Blues" },
        { "title": "Nobody Knows You When You're Down and Out", "artist": "Bessie Smith", "chords": "I-IV-V", "key": "C", "tempo": 75, "genre": "Blues" },
        { "title": "Boom Boom", "artist": "John Lee Hooker", "chords": "I-IV-V", "key": "G", "tempo": 120, "genre": "Delta Blues" },
        { "title": "Blue Jean Blues", "artist": "ZZ Top", "chords": "I-IV-V", "key": "C", "tempo": 80, "genre": "Blues Rock" },
        { "title": "Evil", "artist": "Howlin' Wolf", "chords": "I-IV-V", "key": "E", "tempo": 95, "genre": "Chicago Blues" },
        { "title": "Matchbox Blues", "artist": "Blind Lemon Jefferson", "chords": "I-IV-V", "key": "E", "tempo": 105, "genre": "Delta Blues" },
        { "title": "Crosscut Saw", "artist": "Stevie Ray Vaughan", "chords": "I-IV-V", "key": "G", "tempo": 110, "genre": "Blues Rock" },
        { "title": "Walking By Myself", "artist": "Jimmy Rogers", "chords": "I-IV-V", "key": "A", "tempo": 95, "genre": "Chicago Blues" },
        { "title": "Before You Accuse Me", "artist": "Eric Clapton", "chords": "I-IV-V", "key": "E", "tempo": 85, "genre": "Blues Rock" },
        { "title": "The Sky Is Crying", "artist": "Elmore James", "chords": "I-IV-V", "key": "E", "tempo": 80, "genre": "Chicago Blues" },
        { "title": "You Shook Me", "artist": "Led Zeppelin", "chords": "I-IV-V", "key": "E", "tempo": 90, "genre": "Blues Rock" },
        { "title": "Tin Pan Alley", "artist": "Stevie Ray Vaughan", "chords": "I-IV-V", "key": "F", "tempo": 70, "genre": "Blues Rock" },
        { "title": "I'm a Man", "artist": "Bo Diddley", "chords": "I-IV-V", "key": "G", "tempo": 110, "genre": "Chicago Blues" },
        { "title": "You Upset Me Baby", "artist": "B.B. King", "chords": "I-IV-V", "key": "Bb", "tempo": 95, "genre": "Blues" },
        { "title": "Just Like a Woman", "artist": "Jeff Beck", "chords": "I-IV-V", "key": "E", "tempo": 100, "genre": "Blues Rock" },
        { "title": "Five Long Years", "artist": "Eric Clapton", "chords": "I-IV-V", "key": "G", "tempo": 80, "genre": "Blues Rock" },
        { "title": "All Along the Watchtower", "artist": "Jimi Hendrix", "chords": "I-IV-V", "key": "C", "tempo": 80, "genre": "Blues Rock" },
        { "title": "Rollin' Stone", "artist": "Muddy Waters", "chords": "I-IV-V", "key": "G", "tempo": 100, "genre": "Chicago Blues" },
        { "title": "I'm a King Bee", "artist": "The Rolling Stones", "chords": "I-IV-V", "key": "G", "tempo": 120, "genre": "Blues Rock" },
        { "title": "Red House", "artist": "Albert King", "chords": "I-IV-V", "key": "A", "tempo": 80, "genre": "Blues Rock" },
        { "title": "Still Got the Blues", "artist": "Gary Moore", "chords": "I-IV-V", "key": "Bm", "tempo": 70, "genre": "Blues Rock" },
        { "title": "Born Under a Bad Sign", "artist": "Paul Rodgers", "chords": "I-IV-I-V", "key": "C", "tempo": 110, "genre": "Blues Rock" },
        { "title": "Worried Life Blues", "artist": "Eric Clapton", "chords": "I-IV-V", "key": "A", "tempo": 85, "genre": "Blues Rock" },
        { "title": "Catfish Blues", "artist": "Jimi Hendrix", "chords": "I-IV-V", "key": "E", "tempo": 110, "genre": "Blues Rock" },
        { "title": "Bad Luck Blues", "artist": "Blind Lemon Jefferson", "chords": "I-IV-V", "key": "E", "tempo": 95, "genre": "Delta Blues" },
        { "title": "Fever", "artist": "Little Willie John", "chords": "I-IV-V", "key": "E", "tempo": 120, "genre": "Rhythm and Blues" },
        { "title": "Let Me Love You Baby", "artist": "Buddy Guy", "chords": "I-IV-V", "key": "A", "tempo": 95, "genre": "Chicago Blues" },
        { "title": "Goin' Down Slow", "artist": "Howlin' Wolf", "chords": "I-IV-V", "key": "G", "tempo": 70, "genre": "Chicago Blues" },
        { "title": "Evil Gal Blues", "artist": "Dinah Washington", "chords": "I-IV-V", "key": "G", "tempo": 100, "genre": "Jump Blues" },
        { "title": "I Can't Quit You Baby", "artist": "Led Zeppelin", "chords": "I-IV-V", "key": "F", "tempo": 80, "genre": "Blues Rock" },
        { "title": "Let the Good Times Roll", "artist": "B.B. King", "chords": "I-IV-V", "key": "C", "tempo": 110, "genre": "Electric Blues" },
        { "title": "Blues Before Sunrise", "artist": "Eric Clapton", "chords": "I-IV-V", "key": "E", "tempo": 90, "genre": "Blues Rock" },
        { "title": "Reconsider Baby", "artist": "Fleetwood Mac", "chords": "I-IV-V", "key": "G", "tempo": 80, "genre": "Blues Rock" },
        { "title": "Hound Dog", "artist": "Big Mama Thornton", "chords": "I-IV-V", "key": "C", "tempo": 120, "genre": "Rhythm and Blues" },
        { "title": "Sweet Home Chicago", "artist": "Eric Clapton", "chords": "I-IV-V", "key": "E", "tempo": 120, "genre": "Chicago Blues" },
        { "title": "Stairway to Heaven", "artist": "Led Zeppelin", "chords": "vi-V-IV-I", "key": "A", "tempo": 72, "genre": "Rock" },
        { "title": "Bohemian Rhapsody", "artist": "Queen", "chords": "IV-ii-I-V", "key": "Bb", "tempo": 70, "genre": "Rock" },
        { "title": "Hotel California", "artist": "Eagles", "chords": "ii-VI-V-I-III-bVII-i", "key": "Bm", "tempo": 75, "genre": "Rock" },
        { "title": "Imagine", "artist": "John Lennon", "chords": "I-vi-IV", "key": "C", "tempo": 75, "genre": "Rock" },
        { "title": "Hey Jude", "artist": "The Beatles", "chords": "I-V-IV-bVII", "key": "F", "tempo": 65, "genre": "Rock" },
        { "title": "Sweet Child o' Mine", "artist": "Guns N' Roses", "chords": "I-V-vi-IV", "key": "D", "tempo": 125, "genre": "Rock" },
        { "title": "Yesterday", "artist": "The Beatles", "chords": "I-vi-ii-V", "key": "G", "tempo": 90, "genre": "Rock" },
        { "title": "Smells Like Teen Spirit", "artist": "Nirvana", "chords": "vi-IV-I-V", "key": "F#", "tempo": 116, "genre": "Rock" },
        { "title": "Wonderwall", "artist": "Oasis", "chords": "vi-IV-I-V", "key": "F", "tempo": 87, "genre": "Rock" },
        { "title": "Highway to Hell", "artist": "AC/DC", "chords": "I-V-bVII-IV", "key": "A", "tempo": 118, "genre": "Rock" },
        { "title": "Another Brick in the Wall", "artist": "Pink Floyd", "chords": "vi-IV-I-V", "key": "D", "tempo": 105, "genre": "Rock" },
        { "title": "Johnny B. Goode", "artist": "Chuck Berry", "chords": "I-IV-V", "key": "Bb", "tempo": 168, "genre": "Rock" },
        { "title": "Let It Be", "artist": "The Beatles", "chords": "I-V-VI-IV", "key": "C", "tempo": 68, "genre": "Rock" },
        { "title": "Free Bird", "artist": "Lynyrd Skynyrd", "chords": "G-D-C", "key": "G", "tempo": 72, "genre": "Rock" },
        { "title": "Comfortably Numb", "artist": "Pink Floyd", "chords": "vi-IV-I-V", "key": "Bm", "tempo": 68, "genre": "Rock" },
        { "title": "Purple Haze", "artist": "Jimi Hendrix", "chords": "I-IV-V", "key": "E", "tempo": 105, "genre": "Rock" },
        { "title": "The Sound of Silence", "artist": "Simon & Garfunkel", "chords": "vi-IV-I-V", "key": "Am", "tempo": 86, "genre": "Rock" },
        { "title": "Born to Run", "artist": "Bruce Springsteen", "chords": "I-V-vi-IV", "key": "G", "tempo": 150, "genre": "Rock" },
        { "title": "Light My Fire", "artist": "The Doors", "chords": "vi-IV-I-V", "key": "Em", "tempo": 130, "genre": "Rock" },
        { "title": "Whole Lotta Love", "artist": "Led Zeppelin", "chords": "I-IV-V", "key": "E", "tempo": 89, "genre": "Rock" },
        { "title": "Satisfaction", "artist": "The Rolling Stones", "chords": "I-IV-V", "key": "E", "tempo": 136, "genre": "Rock" },
        { "title": "Sympathy for the Devil", "artist": "The Rolling Stones", "chords": "vi-I-IV-V", "key": "E", "tempo": 112, "genre": "Rock" },
        { "title": "With or Without You", "artist": "U2", "chords": "I-V-vi-IV", "key": "D", "tempo": 110, "genre": "Rock" },
        { "title": "Every Breath You Take", "artist": "The Police", "chords": "vi-IV-I-V", "key": "A", "tempo": 117, "genre": "Rock" },
        { "title": "Piano Man", "artist": "Billy Joel", "chords": "I-V-vi-IV", "key": "C", "tempo": 79, "genre": "Rock" },
        { "title": "More Than a Feeling", "artist": "Boston", "chords": "I-V-vi-IV", "key": "G", "tempo": 108, "genre": "Rock" },
        { "title": "The Joker", "artist": "Steve Miller Band", "chords": "I-IV-V", "key": "G", "tempo": 124, "genre": "Rock" },
        { "title": "Come Together", "artist": "The Beatles", "chords": "I-VI-IV-V", "key": "D", "tempo": 100, "genre": "Rock" },
        { "title": "Back in Black", "artist": "AC/DC", "chords": "I-V-IV", "key": "E", "tempo": 92, "genre": "Rock" },
        { "title": "You Shook Me All Night Long", "artist": "AC/DC", "chords": "I-V-IV", "key": "G", "tempo": 127, "genre": "Rock" },
        { "title": "Smoke on the Water", "artist": "Deep Purple", "chords": "IV-V-I", "key": "G", "tempo": 116, "genre": "Rock" },
        { "title": "Crazy Train", "artist": "Ozzy Osbourne", "chords": "i-bVII-III-bVI", "key": "A", "tempo": 144, "genre": "Rock" },
        { "title": "Paranoid", "artist": "Black Sabbath", "chords": "i-bVII-bVI-V", "key": "E", "tempo": 163, "genre": "Rock" },
        { "title": "Livin' on a Prayer", "artist": "Bon Jovi", "chords": "vi-IV-I-V", "key": "Em", "tempo": 123, "genre": "Rock" },
        { "title": "Don't Stop Believin'", "artist": "Journey", "chords": "vi-IV-I-V", "key": "E", "tempo": 118, "genre": "Rock" },
        { "title": "Sweet Home Alabama", "artist": "Lynyrd Skynyrd", "chords": "D-C-G", "key": "D", "tempo": 98, "genre": "Rock" },
        { "title": "American Woman", "artist": "The Guess Who", "chords": "vi-IV-I-V", "key": "E", "tempo": 120, "genre": "Rock" },
        { "title": "Sweet Emotion", "artist": "Aerosmith", "chords": "IV-I-V", "key": "A", "tempo": 108, "genre": "Rock" },
        { "title": "Walk This Way", "artist": "Aerosmith", "chords": "IV-I-V", "key": "A", "tempo": 106, "genre": "Rock" },
        { "title": "Boys Are Back in Town", "artist": "Thin Lizzy", "chords": "I-V-vi-IV", "key": "D", "tempo": 140, "genre": "Rock" },
        { "title": "Every Rose Has Its Thorn", "artist": "Poison", "chords": "vi-IV-I-V", "key": "D", "tempo": 58, "genre": "Rock" },
        { "title": "More Than Words", "artist": "Extreme", "chords": "vi-IV-I-V", "key": "G", "tempo": 87, "genre": "Rock" },
        { "title": "Here I Go Again", "artist": "Whitesnake", "chords": "vi-IV-I-V", "key": "G", "tempo": 94, "genre": "Rock" },
        { "title": "Jump", "artist": "Van Halen", "chords": "I-V-IV", "key": "C", "tempo": 129, "genre": "Rock" },
        { "title": "Eye of the Tiger", "artist": "Survivor", "chords": "vi-V-IV", "key": "Am", "tempo": 109, "genre": "Rock" },
        { "title": "We Will Rock You", "artist": "Queen", "chords": "VI-V-I", "key": "E", "tempo": 88, "genre": "Rock" },
        { "title": "We Are the Champions", "artist": "Queen", "chords": "I-V-VI-IV", "key": "C", "tempo": 76, "genre": "Rock" },
        { "title": "Dream On", "artist": "Aerosmith", "chords": "vi-IV-I-V", "key": "E", "tempo": 74, "genre": "Rock" },
        { "title": "Welcome to the Jungle", "artist": "Guns N' Roses", "chords": "I-V-vi-IV", "key": "F#", "tempo": 123, "genre": "Rock" },
        { "title": "Rock and Roll All Nite", "artist": "Kiss", "chords": "I-IV-V", "key": "E", "tempo": 100, "genre": "Rock" },
        { "title": "Don't Stop Me Now", "artist": "Queen", "chords": "I-V-vi-IV", "key": "C", "tempo": 156, "genre": "Rock" },
        { "title": "I Love Rock 'n Roll", "artist": "Joan Jett & The Blackhearts", "chords": "I-IV-V", "key": "E", "tempo": 94, "genre": "Rock" },
        { "title": "Sweet Dreams (Are Made of This)", "artist": "Eurythmics", "chords": "vi-IV-I-V", "key": "A", "tempo": 125, "genre": "Rock" },
        { "title": "We're Not Gonna Take It", "artist": "Twisted Sister", "chords": "I-V-IV", "key": "E", "tempo": 70, "genre": "Rock" },
        { "title": "Money for Nothing", "artist": "Dire Straits", "chords": "I-V-vi-IV", "key": "D", "tempo": 126, "genre": "Rock" },
        { "title": "Space Oddity", "artist": "David Bowie", "chords": "I-V-vi-IV", "key": "C", "tempo": 78, "genre": "Rock" },
        { "title": "Ziggy Stardust", "artist": "David Bowie", "chords": "I-IV-V", "key": "A", "tempo": 146, "genre": "Rock" }
    ]
}        